name: Build ORB_SLAM

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        build_type: [Release]
        c_compiler: [gcc]
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
         sudo apt update
         sudo apt install libeigen3-dev libopencv-dev libboost-serialization-dev
         wget https://github.com/stevenlovegrove/Pangolin/archive/refs/tags/v0.9.1.tar.gz -O ../libpangolin.tar.gz
         tar xvf ../libpangolin.tar.gz -C ../
         cd ../Pangolin-0.9.1
         ./scripts/install_prerequisites.sh required
         cmake -B build
         cmake --build build
         cd -

    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Build DBoW2
      run: |
        echo "Configuring and building Thirdparty/DBoW2 ..."
        cd Thirdparty/DBoW2
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        make -j$(nproc)
        
    - name: Build g2o
      run: |
        cd ../../g2o
        echo "Configuring and building Thirdparty/g2o ..."
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        make -j$(nproc)
        
    - name: Build sophus
      run: |
        cd ../../Sophus
        echo "Configuring and building Thirdparty/Sophus ..."
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        make -j$(nproc)
        cd ../../../

    - name: Build ORB_SLAM
      run: |
        echo "Configuring and building ORB_SLAM3 ..."
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        make -j$(nproc)
        cd ..
